version: '3'
services:
  wishlist:
    image: ajb3932/simple-wishlist:latest
    container_name: wishlist
    hostname: wishlist
    ports:
      - 8092:8092
    environment:
      - DBHOST=mongodb:27017
      - CURRENCY=USD
      - LIST_NAME=My Wishlist
      - LIST_TYPE=bday
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: wishlist-db
    hostname: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: